### ISSUE TITLE
ERROR Unable to start com.bitnami.nginx: nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)

### ISSUE THREAD

**Issue by NaturalBornCamper** [bitnami/bitnami-docker-nginx#101]
Using Docker version 18.03.0-ce, build 0520e24302 with the code on the [readme page](https://github.com/bitnami/bitnami-docker-nginx), nginx refuses to start and I get the message:

> ERROR Unable to start com.bitnami.nginx: nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)

**docker-compose.yml**
```
version: '2'

services:
  nginx:
    image: bitnami/nginx:1.10.3-r0
    ports:
      - '80:80'
      - '443:8443'
    volumes:
      - ./code:/app
      - ./my_vhost.conf:/bitnami/nginx/conf/vhosts/my_vhost.conf:ro
```

**my_vhost.conf**
```
server {
  listen 0.0.0.0:8080;
  server_name survey.local;
  root /app;
  index index.htm index.html;
}
```

**Comment by tompizmor** [comment]
Hi @NaturalBornCamper,

I was not able to reproduce the issue with `bitnami/nginx:1.10.3-r0` nor `bitnami/nginx:latest`.
Is there anything specific in your environment that we should know to try to reproduce it?

Also, are you following the README instructions from the `master` branch or from the `1.10.3-r0` tag. The nginx container has changed since that version and so the README has been updated. Please check the README from that version at https://github.com/bitnami/bitnami-docker-nginx/tree/1.10.3-r0 to see if there is anything different that may have affected.

**Comment by NaturalBornCamper** [comment]
I don't know if there's anything specific in my environment, it's a fresh install of docker-tools for Win 10 Home and I had already installed VirtualBox a while ago. The issue actually happens with the simples compose file possible:

```
version: '3'
services:
  web:
    image: bitnami/nginx:latest
    volumes:
      - "./code:/app" #code contains only a basic index.html file
    ports:
      - "80:80"
```

Depending on the volume I set, when looking in the container's `\app` folder

1. <no volumes> makes the `/app` have the default files
2. "./code:/app" makes the  `/app` folder empty
3. "./:/app" makes the  `/app` folder contain random files I deleted a while ago.

Which makes me believe the issue might be with docker, I'm trying to investigate and I'll update the issue/close it when I get more info as even running a complete reset like such makes the app folder contain these deleted files:
```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q) --force
docker volume rm $(docker volume ls -q)
```

**Comment by tompizmor** [comment]
Hi @NaturalBornCamper,

Yes, I think it is a good idea to clean the volumes and start from scratch. 
Just for you to know, I found the explanation to the issue in [this stackoverflow post](https://serverfault.com/questions/771878/nginx-directory-21-is-a-directory).

It seems maybe there were some folders placed inside the `/opt/bitnami/nginx/conf/vhosts/`

**Comment by NaturalBornCamper** [comment]
Hello!

Thanks for your help, I have found out the issue must be with docker since the same issue occurs when I use the official nginx:latest from docker, so I will close this! :)

**Comment by stefangweichinger** [comment]
(Does that issue re-open when I add something?)

I also face that issue as mentioned here:

https://github.com/vmware/photon/issues/819

I did an upgrade to docker-18.0.3:

https://github.com/vmware/photon/issues/723

but still get this:

```
web_1     | 2018/10/15 16:05:06 [crit] 1#0: pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
web_1     | nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
```

my current docker-compose.yml:

```
version: '2'

services:
  web:
    image: 'bitnami/nginx:latest'
    ports:
      - 8083:8080
    volumes:
      - ./code:/app
      - ./nginx/site.conf:/opt/bitnami/nginx/conf/vhosts/my_vhost.conf:ro

  phpfpm:
    image: 'bitnami/php-fpm:latest'
    #ports:
      #- 9001:9000
    volumes:
      - ./code:/app
```

nginx\site.conf is a file, yes:

```
$  tree
.
├── code
│   ├── index.php
│   ├── README.txt
│   ├── my_app.php

├── docker-compose.yml
└── nginx
    └── site.conf
```

I am not sure where the/my mistake is. pls advise ...
