### ISSUE TITLE
pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)

### ISSUE THREAD

**Issue by stefangweichinger** [bitnami/bitnami-docker-nginx#108]
I also face that issue as mentioned here:

https://github.com/vmware/photon/issues/819

I did an upgrade to docker-18.0.3:

https://github.com/vmware/photon/issues/723

but still get this:

```
web_1     | 2018/10/15 16:05:06 [crit] 1#0: pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
web_1     | nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
```

my current docker-compose.yml:

```
version: '2'

services:
  web:
    image: 'bitnami/nginx:latest'
    ports:
      - 8083:8080
    volumes:
      - ./code:/app
      - ./nginx/site.conf:/opt/bitnami/nginx/conf/vhosts/my_vhost.conf:ro

  phpfpm:
    image: 'bitnami/php-fpm:latest'
    #ports:
      #- 9001:9000
    volumes:
      - ./code:/app
```

nginx\site.conf is a file, yes:

```
$  tree
.
├── code
│   ├── index.php
│   ├── README.txt
│   ├── my_app.php

├── docker-compose.yml
└── nginx
    └── site.conf
```

I am not sure where the/my mistake is. pls advise ...

EDIT: I even upgraded my photon OS to docker-18.06.1 and removed all volumes. Same result :-(

_Originally posted by @stefangweichinger in https://github.com/bitnami/bitnami-docker-nginx/issues/101#issuecomment-429919560_

**Comment by stefangweichinger** [comment]
I tried plain "docker run" as well and used an absolute path in the volume definition, with nginx:latest and nginx:1.14 ->

vs upstream 18.0.6.1:

```
docker run --name nginx -v /home/sgw/projects/docker/__learning/nginx/site.conf:/opt/bitnami/nginx/conf/vhosts/my_vhost.conf:ro  bitnami/nginx:1.14

[..]

2018/10/15 16:59:36 [crit] 1#0: pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
```

Same command works on my local docker-service.

**Comment by juan131** [comment]
Hi @stefangweichinger 

**/opt/bitnami/nginx/conf/vhosts/my_vhost.conf** expects a file instead of a directory. You're mounting a directory with both your php code and the NGINX configuration file. However, you're supposed to inject just the NGINX configuration file for the specific virtual host.

You should only mount your php app on the **php-fpm** container.

**Comment by stefangweichinger** [comment]
So you want me to remove the line 

`- ${PWD}/code:/app`

from the "web" service, correct?

Did so, fails as well. I understand the directory/file-conflict but I don't see the mistake. The docs for bitnami/nginx mention mounting a file as well. Same path ..

**Comment by juan131** [comment]
Hi @stefangweichinger 

> So you want me to remove the line

No, that's fine (at least on the php-fpm container). The problem is not in the **php-fpm** configuration. 

The problem is that you've mounted a directory:

```
      - ./nginx/site.conf:/opt/bitnami/nginx/conf/vhosts/my_vhost.conf:ro
```

And you should have mounted just a file. 

**./nginx/site.conf** should be a single file with the NGINX configuration.

**Comment by stefangweichinger** [comment]
rm-ed nginx subdir and edited docker-compose.yml:

```
version: '3.4'

services:
  web:
    image: 'bitnami/nginx:latest'
    ports:
      - 8083:8080
    volumes:
      - /home/sgw/projects/docker/__learning/site.conf:/opt/bitnami/nginx/conf/vhosts/my_vhost.conf

  phpfpm:
    image: 'bitnami/php-fpm:latest'
    volumes:
      - ./code:/app
```

fails as well. pls advise, thanks ...

**Comment by juan131** [comment]
Hi @stefangweichinger 

What error do you obtain when you mount a file instead of a directory? 

I'm pretty sure you didn't find the error below:

```
2018/10/15 16:59:36 [crit] 1#0: pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
```

**Comment by stefangweichinger** [comment]
I agree completely. And I repeat: I try to mount a file. That is the issue here!

**Comment by stefangweichinger** [comment]
I installed another debian server with docker.service and tested against it, same error.  Maybe you can share a link to a git-repo with a working example (docker-compose.yml with nginx and fpm services, plus some nginx conf file). 

To me it looks as if the behavior is different when I connect to the docker-service via tcp:// as with:

> export DOCKER_HOST=tcp://192.168.0.1:2375
> docker-compose up  # here it fails as described

vs. running it on my local machine (where it works!).
thanks

**Comment by juan131** [comment]
Hi @stefangweichinger 

These are the steps I followed:

I created a simple php site:

```
$ cat > /tmp/php-info.php <<'EOF'
<?php
phpinfo();
?>
EOF
```

Then, I created a simple vhost:

```
$ cat > /tmp/my-app.conf <<'EOF'
server {
  listen 0.0.0.0:8080;
  server_name myapp.com; 
  
  root /app;

  location / {
    try_files $uri $uri/index.php;
  }

  location ~ \.php$ {
    fastcgi_pass php-fpm:9000;
    fastcgi_index index.php;
    include fastcgi.conf;
  }
}
EOF
```

And I used the **docker-compose.yaml** below:

```
version: '2'

services:
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - php-fpm
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'nginx_data:/bitnami'
      - /tmp/my-app.conf:/opt/bitnami/nginx/conf/vhosts/my_vhost.conf:ro
  php-fpm:
    image: 'bitnami/php-fpm:latest'
    volumes:
      - /tmp/php-info.php:/app/php-info.php:ro

volumes:
  nginx_data:
    driver: local
```

I run `docker-compose up -d` and access to NGINX at http://127.0.0.1/php-info.php and I obtained the php info site.

**Comment by stefangweichinger** [comment]
thank you. cp-ied your example, works with local docker.service, does not work after `export DOCKER_HOST=tcp://192.168.0.1:2375`. Same behavior as with my own project dir.

Copied the 3 files up via scp, ssh-ed into that $DOCKER_HOST, ran `docker-compose up` there locally, result:

```
root@docker:~# docker-compose up
Creating network "root_default" with the default driver
Creating volume "root_nginx_data" with local driver
Creating root_php-fpm_1 ... done
Creating root_nginx_1   ... done
Attaching to root_php-fpm_1, root_nginx_1
nginx_1    | 
nginx_1    | Welcome to the Bitnami nginx container
nginx_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
nginx_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
nginx_1    | Send us your feedback at containers@bitnami.com
nginx_1    | 
nginx_1    | INFO  ==> nginx.conf not found. Applying bitnami configuration...
nginx_1    | INFO  ==> Starting nginx... 
nginx_1    | 2018/10/18 17:50:38 [crit] 1#0: pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
nginx_1    | nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
```

upstream:

```
root@docker:~# docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 4
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.801GiB
Name: docker
ID: KBB4:XPIR:MIWN:KKTE:O6FM:O56I:YTDW:K6IN:DU3H:RCPZ:54MW:Y5TV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by juan131** [comment]
HI @stefangweichinger 

What do you obtain when running the command below?

```
docker-compose run nginx ls -la /opt/bitnami/nginx/conf/vhosts/
```

**Comment by juan131** [comment]
Hi @stefangweichinger 

Could you please run the command below and share the output?

```
docker-compose run nginx ls -la /opt/bitnami/nginx/conf/vhosts/
```

**Comment by stefangweichinger** [comment]
I quote the docker-compose.yml as well for reference, it has traefik-related config in there now:

```
version: '2'

services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 8083:8080
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:stbvv.docker.local"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.default.protocol=http"
    volumes:
        #- ./nginx/site.conf:/opt/bitnami/nginx/conf/vhosts/site.conf
        #- ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/code:/app

### second service skipped here

```

Your command shows that the subdir "vhosts" is missing, right! ->

```
$ docker-compose run nginx ls -la /opt/bitnami/nginx/conf/vhosts/ 

Welcome to the Bitnami nginx container

[..]

ls: cannot access '/opt/bitnami/nginx/conf/vhosts/': No such file or directory
```

"conf" exists:

```
$ docker-compose run nginx ls -la /opt/bitnami/nginx/conf/

Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

total 72
drwxrwxr-x 2 root root 4096 Oct 19 03:50 .
drwxrwxr-x 8 root root 4096 Oct 19 03:50 ..
-rw-rw-r-- 1 root root 1077 Aug 23 13:41 fastcgi.conf
-rw-rw-r-- 1 root root 1077 Aug 23 13:41 fastcgi.conf.default
-rw-rw-r-- 1 root root 1007 Aug 23 13:41 fastcgi_params
-rw-rw-r-- 1 root root 1007 Aug 23 13:41 fastcgi_params.default
-rw-rw-r-- 1 root root 2837 Aug 23 13:41 koi-utf
-rw-rw-r-- 1 root root 2223 Aug 23 13:41 koi-win
-rw-rw-r-- 1 root root 5170 Aug 23 13:41 mime.types
-rw-rw-r-- 1 root root 5170 Aug 23 13:41 mime.types.default
-rw-rw-r-- 1 root root 2656 Aug 23 13:41 nginx.conf.default
-rw-rw-r-- 1 root root  636 Aug 23 13:41 scgi_params
-rw-rw-r-- 1 root root  636 Aug 23 13:41 scgi_params.default
-rw-rw-r-- 1 root root  664 Aug 23 13:41 uwsgi_params
-rw-rw-r-- 1 root root  664 Aug 23 13:41 uwsgi_params.default
-rw-rw-r-- 1 root root 3610 Aug 23 13:41 win-utf
```

This means that the [README](https://github.com/bitnami/bitnami-docker-nginx#step-2-mount-the-configuration-as-a-volume) contains wrong information, correct?

Now how to correct that? Thanks, Stefan
