### ISSUE TITLE
Permission issues nginx and phpfpm

### ISSUE THREAD

**Issue by immertroll** [bitnami/bitnami-docker-nginx#124]
Hello,

I use nginx image in combination with phpfpm image. I mount my application with:
```
./docker/dockervolumes/website/app:/app
```
to the nginx and the phpfpm container.

If I try to reach my site the container logs: 
```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Failed to save file /app/cache/compiled/files/d022677791bb0b57b746fd601400fcce.yaml.php in /app/vendor/rockettheme/toolbox/File/src/File.php:351
```

first try
After chown to 1001:1001 and chmod for rw permission inside the app-folder, nothing changed.

second try
change permisson for all instead of only owner and group, it works.
But that's not a good solution. What's is the correct nginx user?!?
If I do
```
ps aux | grep -v root | grep nginx | cut -d\  -f1 | sort | uniq
```
I get
`1001`

Any hints?

**Comment by juan131** [comment]
Hi @immertroll 

Could you share the `docker-compose.yaml` you're using to deploy NGINX + PHP-FPM? I want to reproduce the issue son I can identify what's going on with the permissions setup.

**Comment by immertroll** [comment]
Hi @juan131 

here is the content of my docker-compose file.

```
version: '2'
services:
  phpfpm:
    image: 'bitnami/php-fpm:7.3.8'
    container_name: phpfpm
    networks:
      - mywebsiteNetwork
    volumes:
      - ./docker/dockervolumes/nginx/app:/app
  nginx:
    image: 'bitnami/nginx:1.16.1'
    container_name: nginx
    depends_on:
      - phpfpm
    networks:
      - mywebsiteNetwork
    ports:
      - '8194:8080'
    volumes:
      - ./docker/dockervolumes/nginx/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/mywebsite.conf
      - ./docker/dockervolumes/nginx/app:/app

networks:
  mywebsiteNetwork:
    driver: bridge
```

Thank you for your help
