### ISSUE TITLE
Best practices to run in PSP

### ISSUE THREAD

**Issue by boskiv** [bitnami/bitnami-docker-nginx#139]
**Description**

How run this image agains stricly configured kubernetes clusters. Is there some sort of recomendations or examples ?

For example we have     readOnlyRootFilesystem: true  
and When I run 
```
helm install bitnami/nginx --generate-name
```
I've got in logs:
```
Pods/nginx-1589908001-588758b6fd-fv7qb
[nginx-1589908001-588758b6fd-fv7qb nginx] /opt/bitnami/scripts/libnginx.sh: line 61: cannot create temp file for here-document: Read-only file system
[nginx-1589908001-588758b6fd-fv7qb nginx] [38;5;6m [38;5;5m18:24:14.03 [0m
[nginx-1589908001-588758b6fd-fv7qb nginx] [38;5;6m [38;5;5m18:24:14.03 [0m[1mWelcome to the Bitnami nginx container[0m
[nginx-1589908001-588758b6fd-fv7qb nginx] [38;5;6m [38;5;5m18:24:14.13 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-nginx[0m
[nginx-1589908001-588758b6fd-fv7qb nginx] [38;5;6m [38;5;5m18:24:14.13 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-nginx/issues[0m
[nginx-1589908001-588758b6fd-fv7qb nginx] [38;5;6m [38;5;5m18:24:14.13 [0m
[nginx-1589908001-588758b6fd-fv7qb nginx] [38;5;6m [38;5;5m18:24:14.14 [0m[38;5;2mINFO [0m ==> ** Starting NGINX setup **
[nginx-1589908001-588758b6fd-fv7qb nginx] /opt/bitnami/scripts/libnginx.sh: line 61: cannot create temp file for here-document: Read-only file system
[nginx-1589908001-588758b6fd-fv7qb nginx] [38;5;6m [38;5;5m18:24:14.24 [0m[38;5;2mINFO [0m ==> Validating settings in NGINX_* env vars...
[nginx-1589908001-588758b6fd-fv7qb nginx] [38;5;6m [38;5;5m18:24:14.33 [0m[38;5;2mINFO [0m ==> Initializing NGINX...
[nginx-1589908001-588758b6fd-fv7qb nginx] /opt/bitnami/scripts/libnginx.sh: line 150: NGINX_TMPDIR: unbound variable
[nginx-1589908001-588758b6fd-fv7qb nginx] /opt/bitnami/scripts/libnginx.sh: line 27: NGINX_TMPDIR: unbound variable
```

**Comment by dani8art** [comment]
Hi @boskiv , yes that happened because we use some `tmp` directories for managing PID and some other stuff, and it could be fixed if `emptyDir` volumes are mounted on `/opt/bitnami/nginx/tmp` and `/tmp`. I'm going to work on extending the chart to solve this problem.

I'll keep updated, thank you for your feedback.

**Comment by dani8art** [comment]
Having this new feature, you would be able to add the following to the `values.yaml` or via `--set` parameter so that you will be able to run the chart using `readOnlyRootFilesystem: true`:

```yaml
## Array to add extra volumes (evaluated as a template)
##
extraVolumes:
  - name: root-tmp
    emptyDir: {}
  - name: bitnami-tmp
    emptyDir: {}

## Array to add extra mounts (normally used with extraVolumes, evaluated as a template)
##
extraVolumeMounts:
  - name: root-tmp
    mountPath: /tmp
  - name: bitnami-tmp
    mountPath: /opt/bitnami/nginx/tmp
```
