### ISSUE TITLE
Unable to set up ssl in nginx

### ISSUE THREAD

**Issue by Bharath3697** [bitnami/bitnami-docker-nginx#159]
**Description**

I need to run nginx as non-root user and have enabled ssl (self-signed certs) for bitnami/nginx in docker and it is not working. The response i get is “This site can’t be reached localhost unexpectedly closed the connection.” But works fine without ssl.

**Steps to reproduce the issue:**

**Docker file :**
```
FROM bitnami/nginx
COPY ./config/nginx/conf.d/django.conf /opt/bitnami/nginx/nginx.conf
COPY ./certs/ /opt/bitnami/nginx/conf/bitnami/certs/
EXPOSE 443
ENTRYPOINT [ “/opt/bitnami/scripts/nginx/entrypoint.sh” ]
CMD [ “/opt/bitnami/scripts/nginx/run.sh” ]

```

**django.conf :** 
```
server {
listen 443 ssl;

ssl_certificate      /opt/bitnami/nginx/conf/bitnami/certs/server.crt;
ssl_certificate_key  /opt/bitnami/nginx/conf/bitnami/certs/server.key;

ssl_session_cache    shared:SSL:1m;
ssl_session_timeout  5m;

ssl_ciphers  HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers  on;

location / {
    root   /app;
    index  index.html index.htm;
}
}
```
**docker-compose.yml :** 

```
version: "3"
services:
  nginx_test:
    build:
      context: .
      dockerfile: Dockerfile_ng
    container_name: ng01_test
    restart: always
    ports:
      - "443:443"
```

**Describe the results you received:**

Nginx container starts and running but no connection is reaching there.

This site can’t be reached
localhost unexpectedly closed the connection.

**Version**

docker version : 19.03.12
