### ISSUE TITLE
cannot load certificate key error at nginx startup

### ISSUE THREAD

**Issue by eurydice76** [bitnami/bitnami-docker-nginx#164]
Hello,

I try to apply the recipe provided in the README of your project in order to setup a nginx reverse proxy on top of a microservice whose name is matlab-license running on port 3000. When running `docker-compose up` I get the following error message at nginx start up.

`nginx             | 2021/10/08 09:56:58 [emerg] 1#1: cannot load certificate key "/certs/server.key": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/certs/server.key','r') error:2006D002:BIO routines:BIO_new_file:system lib)`

Here is my docker-compose file:
```

version: "3"

services:
    matlab-license:
        build: .
        restart: on-failure
        ports:
            - 3000:3000
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ./logs:/var/log/matlab-license:rw
        env_file: .env

    proxy:
        container_name: nginx
        image: bitnami/nginx:latest
        restart: on-failure
        volumes:
            - ./conf/nginx/certs:/certs
            - ./conf/nginx/conf/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf:ro
            - ./logs:/var/log/matlab-license:rw
        ports:
            - 80:8080
            - 443:8443
        depends_on:
            - matlab-license
```    
and here is my nginx server block  file:

```
    server {
        # listen on port 80 (http)
        listen 8080;
        location / {
            # redirect any requests to the same URL but on https
            return 301 https://$host$request_uri;
        }
    }

    server {
        # listen on port 443 (https)
        listen 8443 ssl;

        # location of the self-signed SSL certificate
        ssl_certificate bitnami/certs/server.crt;
        ssl_certificate_key bitnami/certs/server.key;

        # write access and error logs to /var/log
        access_log /var/log/matlab-license/matlab-license_access.log;
        error_log /var/log/matlab-license/matlab-license_error.log;

        location / {
            # The target name (here webservices) must match the name of the corresponding service in the docker-compose file
            proxy_pass http://matlab-license:3000;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 
            # Kill cache
            add_header Last-Modified $date_gmt;
            add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            if_modified_since off;
            expires off;
            etag off;
        }
    }
```

would you see what is wrong with my settings ? thank you very much
