### ISSUE TITLE
Internal container to container HTTP(S) calls with virtual hostname without adding the 8080 or 8443 ports to the hostname

### ISSUE THREAD

**Issue by kdevan** [bitnami/bitnami-docker-nginx#170]
**Description**

This is not an issue with the container, everything is running perfectly and it's been a great experience running Bitnami containers, so if this is considered off-topic I understand.

I'm wondering if there's a recommended way to handle internal container to container HTTP(S) calls without adding the 8080 or 8443 to the end of the hostname? When calling from the host it works fine because the ports 80 and 443 are forwarded correctly. But when calling from another container, in this case a Bitnami nodejs container, it does not work to use the hostname because HTTP(S) calls will use ports 80 or 443 by default and internally those are not mapped to 8080 and 8443.

- Adding those ports to the end of the hostname in code is not ideal because it becomes convoluted code wise to make sure that calls from the host do not include ports and calls internally do include ports.
- I can't set the ports to simply use 80:80 and 443:443 because the container does not run as root (which I understand is a good thing for security, just mentioning that it's not a solution in this case).
- I can't seem to use extra_hosts in the docker-compose file for the nodejs service which seems like it would be a great solution since it allows adding entries to the hosts file, but it only allows hostname -> IP address mapping, and IP address is not ideal since it changes every time docker-compose is changed/run.
- I can't seem to add the entry to the hosts file manually during the building of the image because docker needs to be aware of anything done to the hosts file. I've tried and it doesn't work.

I understand this issue is not specific to this container and more of a general docker issue but since the solution here might depend on how these containers are built, I thought I'd ask here. This seems like it should be a common use case so I feel like I'm missing something obvious here...

**Steps to reproduce the issue:**

Here's the relevant portions of the docker-compose file:
```
version: '3.9'
services:
    web:
        container_name: web
        image: 'bitnami/nginx:latest'
        restart: always
        ports:
          - '80:8080'
          - '443:8443'
        volumes:
          - ./apps/apis:/app:ro
          - ./web/certs:/certs
          - ./web/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
          - ./web/custom.d:/opt/bitnami/nginx/conf/custom.d:ro
          - ./web/conf.d:/opt/bitnami/nginx/conf/server_blocks:ro
          - ./web/h5bp:/opt/bitnami/nginx/conf/h5bp:ro
        networks:
          my-net:
            aliases:
              - local.website1.com
              - local.website2.com
        depends_on:
          - client
    client:
        container_name: client
        image: 'bitnami/node:17'
        restart: always
        environment:
          NODE_EXTRA_CA_CERTS: /certs/chain.pem
        volumes:
          - ./apps/clients:/app/apps/clients
          - ./packages/js:/app/packages/js
          - ./web/certs:/certs
        tty: true
        networks:
          - my-net
networks:
  my-net:
    name: my-net
    driver: bridge
```

**Describe the results you received:**

By including the hostnames as aliases on the nginx container, the HTTP(S) calls from the nodejs container route to the nginx container correctly, but then use ports 80 and 443 which does not work.

`FetchError: request to https://local.website1.com failed, reason: connect ECONNREFUSED 172.28.0.8:443`

**Describe the results you expected:**

I'm hoping for a way to do internal HTTP(S) calls without having to include the port in the hostname.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:27 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker-compose version`:

```
docker-compose version 1.27.4, build unknown
docker-py version: 4.4.4
CPython version: 3.9.7
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
```

**Comment by kdevan** [comment]
Finally got it. For anyone who might be having the same issue:

I needed to remove the aliases on the web service -

```
web:
    networks:
          my-net:
            aliases:
              - local.website1.com
              - local.website2.com
```

And add extra_hosts using "host-gateway" which works instead of using an IP address and points to your host. Since the host is set up to correctly forward to nginx, it all works!

```
client:
    extra_hosts:
      - "local.api.shopexperiments.com:host-gateway"
      - "local.shopexperiments.com:host-gateway"
```
