### ISSUE TITLE
vhost problem

### ISSUE THREAD

**Issue by robbygallo** [bitnami/bitnami-docker-nginx#91]
I have tried to map my local vhostv folder to nginx vhosts folder.
I get this error

```
INFO  ==> Starting nginx... 
nginx_1    | nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx_1    | 2017/11/19 10:12:10 [emerg] 21#0: bind() to 0.0.0.0:80 failed (13: Permission denied)

```

my vhost
```
server {
  listen 80;
  server_name test.dev;

  root /app;

  location / {
    index index.php;
  }

  location ~ \.php$ {
    # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
    fastcgi_pass php-fpm:9000;
    fastcgi_index index.php;
    include fastcgi.conf;
  }
}
```

my docker-compose
```
version: '2'

services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/www:/app
      - ./apache/vhosts:/bitnami/apache/conf/vhost
      - ./apache/logs:/bitnami/apache/logs
    depends_on:
      - php-fpm
    networks:
      - app-tier

  nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/www:/app
      - ./nginx/vhosts/default.conf:/bitnami/nginx/conf/vhosts/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-tier

  php-fpm:
    image: 'bitnami/php-fpm:latest'
    ports:
      - '9000:9000'
    volumes:
      - ~/www:/app
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge](url)
```

Can you help me please

**Comment by robbygallo** [comment]
I have solved to set 
```
nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '80:8080'
      - '443:8443'
```

and 

```
server {
  listen 8080;
  server_name test.dev;
```
