### ISSUE TITLE
bind() to 0.0.0.0:80 failed (13: Permission denied)

### ISSUE THREAD

**Issue by julian-linux** [bitnami/bitnami-docker-nginx#96]
on vagrant "ubuntu/trusty64"

file: docker-compose.yml
```
version: "2"
networks:
 app-tier:
  driver: bridge
services:
 api:
  image: 'bitnami/php-fpm:latest'
  networks:
   - app-tier
  volumes:
   - /app/api_lumen/public:/app
   -  /vagrant/docker/api/php-fpm.conf:/opt/bitnami/php7.2/etc/php-fpm.conf
  restart: always
  ports:
   - "9000:9000"
 nginx:
  image: 'bitnami/nginx:latest'
  depends_on:
   - api
  networks:
   - app-tier
  ports:
   - '80:80'
   - '443:443'
  volumes:
    - /vagrant/docker/web/nginx/nginx.conf:/bitnami/nginx/conf/vhosts/localhost.conf
```

nginx config file
```
upstream backend {
        server api:9000;
}
server {
        listen 0.0.0.0:80;
        index index.php index.html;
        server_name web;
        error_log "/opt/bitnami/nginx/logs/myapp-error.log";
        access_log  "/opt/bitnami/nginx/logs/myapp-access.log";
        root /app;

        location / {
            try_files $uri $uri/index.php;
        }

        location ~ \.php$ {
            # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
            fastcgi_pass backend;
            fastcgi_index index.php;
            include fastcgi.conf;
        }
}
```

and running

 `sudo docker-compose up`

result

```
nginx_1  | INFO  ==> Starting nginx...
nginx_1  | 2018/02/16 04:13:43 [emerg] 19#0: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
docker_nginx_1 exited with code 1
```

**Comment by juan131** [comment]
You should use:

```
  ports:
   - '80:8080'
   - '443:8443'
```

And edit the `nginx.conf` file so it listen on the port 8080

```
server {
        listen 0.0.0.0:8080;
        ...
```

It doesn't have privileges to bind the port 80.

**Comment by sergeifilippov** [comment]
As far as I know, nginx needs to be `run as root` in order to bind to port `80`.

Since release `1.12.1-r2`, nginx daemon is being run as user `1001`.

> 1.12.1-r2

> The nginx container has been migrated to a non-root container approach. Previously the container run as root user and the nginx daemon was started as nginx user. From now own, both the container and the nginx daemon run as user 1001. As a consequence, the configuration files are writable by the user running the nginx process.

**Comment by aravindgv** [comment]
I had a similar issue. I resolved it by running sudo
Since your image is running as non-root user so you are not able to bind to port 80 which is a privilege port only root user can run. Starting nginx as sudo should solve this issue as shown below

command: [ "/bin/bash", "-c", "sudo nginx -g 'daemon off;'" ]

**Comment by andresbono** [comment]
Hi @aravindgv, thanks for sharing your solution 👍 However, https://github.com/bitnami/bitnami-docker-nginx/issues/96#issuecomment-366199235 is the recommended way to handle this. Take a look in case you want to change your setup!

**Comment by markserrano915** [comment]
I'm using this image on my Kubernetes cluster via Helm Chart.

I update the `nginx.conf` to listen on `8888`

```
listen 0.0.0.0:8888;
```

Then I updated my `values.yaml` in Helm Chart to match the port:

```
service:
  name: foo-app
  type: NodePort
  externalPort: 8888
  internalPort: 8888
```
